version: '2.3'

networks:
  web:
    external: true
  back:
    driver: bridge

services:
  web:
    image: blackojack/laravel
    restart: always
    volumes:
      - ./redis:/var/redis/data
      - ./www:/www
    labels:
      - "traefik.backend=laravel"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:demodns.sibdata.ru"
      - "traefik.enable=true"
      - "traefik.port=80"
    env_file:
      - system.env
    networks:
      - back
      - web
    expose:
      - "80"
    ports:
      - "2222:22"
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    env_file:
      - system.env
      - mysql.env
    networks:
      - back:
        aliases:
          - db
    expose:
      - "3306"
